subclassOf: null
classNamePattern: null
#  - java.io.Serializable
allowPhantom: false
notations:
#  - java.io.Serializable
  - org.springframework.context.annotation.Configuration

# ( method-name-pattern || method-subsig ) && invoke-method
