extend:
  # source
  - taint-config/web/tomcat-web.yaml
  # sink
  - taint-config/basic/defineClass.yaml
  # transfer
  - taint-config/basic/default-transfers.yaml
  # vulns
  - taint-config/vulns
  # 原生反序列化
  - taint-config/basic/jnd-deser.yaml
