extend:
  # source
  - taint-config/web/tomcat-web.yml
  # sink
  - taint-config/basic/defineClass.yml
  # transfer
  - taint-config/basic/default-transfers.yml
  # vulns
  - taint-config/vulns
  # 原生反序列化
  - taint-config/basic/jnd-deser.yml
